// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0--rc2
// source: proto/order/order.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UsdtPayService_CreateOrder_FullMethodName = "/order.UsdtPayService/CreateOrder"
)

// UsdtPayServiceClient is the client API for UsdtPayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsdtPayServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
}

type usdtPayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsdtPayServiceClient(cc grpc.ClientConnInterface) UsdtPayServiceClient {
	return &usdtPayServiceClient{cc}
}

func (c *usdtPayServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, UsdtPayService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsdtPayServiceServer is the server API for UsdtPayService service.
// All implementations must embed UnimplementedUsdtPayServiceServer
// for forward compatibility.
type UsdtPayServiceServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	mustEmbedUnimplementedUsdtPayServiceServer()
}

// UnimplementedUsdtPayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsdtPayServiceServer struct{}

func (UnimplementedUsdtPayServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedUsdtPayServiceServer) mustEmbedUnimplementedUsdtPayServiceServer() {}
func (UnimplementedUsdtPayServiceServer) testEmbeddedByValue()                        {}

// UnsafeUsdtPayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsdtPayServiceServer will
// result in compilation errors.
type UnsafeUsdtPayServiceServer interface {
	mustEmbedUnimplementedUsdtPayServiceServer()
}

func RegisterUsdtPayServiceServer(s grpc.ServiceRegistrar, srv UsdtPayServiceServer) {
	// If the following call panics, it indicates UnimplementedUsdtPayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UsdtPayService_ServiceDesc, srv)
}

func _UsdtPayService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsdtPayServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsdtPayService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsdtPayServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsdtPayService_ServiceDesc is the grpc.ServiceDesc for UsdtPayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsdtPayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.UsdtPayService",
	HandlerType: (*UsdtPayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _UsdtPayService_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/order/order.proto",
}
